settings:
  legacy:
    force: false
    interval: 0s
server:
  status: false
  open: false
  port: 8080
  host: localhost
schema:
- name: go
  path: .
  commands: {}
  watcher:
    extensions:
    - go
    paths:
    - /
    ignored_paths:
    - .git
    - .realize
    - vendor
