version: '3'
services:
  app:
    build:
      context: .
      dockerfile: docker/go/Dockerfile
    environment:
      IN_DOCKER: 1
      TZ: Asia/Tokyo
    volumes:
      - ./:/go
    ports:
      - "8080:8080"
    tty: true
    stdin_open: true
